# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/HW101.COJTHW/COJT/display/display.xdc

# IP: C:/Users/HW101.COJTHW/COJT/display/disp_ip/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] -quiet

# XDC: c:/users/hw101.cojthw/cojt/display/display.tmp/display_v1_0_project/display_v1_0_project.gen/sources_1/ip/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/users/hw101.cojthw/cojt/display/display.tmp/display_v1_0_project/display_v1_0_project.gen/sources_1/ip/fifo_48in24out_1024depth/fifo_48in24out_1024depth_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
